### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by marykatefain** [liberationphilly/liberationphilly.org#14]

**Comment by alexgleason** [comment]
![screenshot from 2017-09-19 11 57 28](https://user-images.githubusercontent.com/3639540/30602151-ba28e1e2-9d31-11e7-9870-47d46234800e.png)

Looks like the nav fits just barely on a Nexus 5 screen. Honestly this was better than I expected.

There are a few ways you could improve it, though.

1. Have a smarter nav. Break it up into two pieces. Make one of them stay on top in mobile and the other stick to the footer.
2. Have less navigation items in general. Consolidate pages together. The whole of "contact" could go in a global footer, but you'd have to handle it differently so it's not quite as big.
3. Let the nav extend beyond the screen horizontally. Handle this either like Android (have an ellipses button on the right that opens a popup with the remaining items; requires some JS) or just let it straight up overflow with a scrollbar like [elementary.io](https://elementary.io/). I'm a big fan of this option in some form. The latter is simpler but perhaps less obvious. The former is complicated and maybe error prone.

**Comment by marykatefain** [comment]
@alexgleason - These are good ideas! Thanks! I especially like the idea of putting all the contact info on the footer. That could definitely be done reasonably.
