### ISSUE TITLE
Upcoming events "view all" could be handled differently

### ISSUE THREAD

**Issue by alexgleason** [liberationphilly/liberationphilly.org#18]
I think the "view all" button conflicts with the "subscribe" button here.

![screenshot from 2017-09-20 10 24 35](https://user-images.githubusercontent.com/3639540/30649304-ec2fa7a4-9ded-11e7-8891-d0af3b48b951.png)

An option is to move the "view all" button next to the headline.

![screenshot from 2017-09-20 10 23 33](https://user-images.githubusercontent.com/3639540/30649280-dbd75cf8-9ded-11e7-9871-5d52b63670b0.png)

It's worth noting that we might not even have 4 events at any given time. How do you expect this to behave? Do the events expand open right on the page, or is there a separate page with all the events?

Maybe having the fourth tile be a "view all" is even better.

**Comment by marykatefain** [comment]
I agree with moving the view all button up, that definitely looks better.

I think we should always have 4 events at once, and it we don't we better get our act together. (Even if it is just DoAs for the next 3 months).
