### ISSUE TITLE
Home page event sign up buttons

### ISSUE THREAD

**Issue by marykatefain** [liberationphilly/liberationphilly.org#2]
These should open some way for the user to sign up for the relevant event. Simple pop up on page? Or bring user to more detailed event page?

Attach back-end

**Comment by alexgleason** [comment]
What would signing up entail? As in, how do you envision it working?

The feature doesn't seem necessary. The site can just show the latest events and people can be notified through email about updates. Are you trying to get a head count?

**Comment by marykatefain** [comment]
Yeah, a head count primarily. But also just the psychological aspect of being obligated to go because you said you would.  Eventually maybe even the social aspect of seeing how many others have rsvped (like on meetup), but I old boost that until the numbers look good.

Right now full event details and rsvp info are on the events page, but these aren't really linked in any way.

So I guess I'm asking if we want this button to bring people to a page with the details where they can say they are going, and if so is that one page with all events, or does each event generate a new page? Or would we rather people rsvp right on the home page? If so, how do they get the details?

I can see this going like 14 different ways, and am very torn.

**Comment by alexgleason** [comment]
You might want to consider making it say "RSVP" or "I'm going!" then instead of "sign up" since "sign up" is less direct and could entail more things.

I could envision it asking for a name, and that's it. It then updates the count of who all is going.

That said, is this a priority for v1 of the website? I feel that we can do without it for the first iteration.

**Comment by marykatefain** [comment]
I like the idea of changing it to say "RSVP". 

I do think this is a priority for a few reasons:

1) People may not want to subscribe to all our event emails, so this gives us a way to get contact info for people who are just interested in one type of event (like LP meetups, of volunteer days). This way we can continue to market those events to them when they come up. (I think we should ask for name and email).

2) We really do need headcounts for a lot of these events. Previously we would go by the facebook "going" count or by talking to people one on one, but as we grow we will need to have more accurate counts. The most obvious example of this is Sanctuary days, which will require letting them know in advance how many volunteers to expect. Other examples include having enough food at meetups, enough signs at protests, and transportation arranged for everyone if we ever plan to drive somewhere. Obviously having "too many people" is a great problem to have, but nonetheless there is no reason to put us in that position now when we could easily have a method for RSVPing.

Soooooo what do you think? I guess I am leaning towards this:
 - the calendar icon links to the event details page
 - sign up button opens a popup with basic event info and rsvp name and email fields
 - upon submitting they get an email with full details
 - reminder email prior to event
 - optional phone # field and ability for people to opt into text reminders, maybe??
